services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=996
      - PGID=988
      - TZ=Etc/America/New_York
      - MONGO_USER=unifi
      - MONGO_PASS=unifimongopass
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      - MONGO_TLS=
    volumes:
      - /mnt/data/docker/volumes/unifi-network-application/data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8081:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    restart: unless-stopped
    depends_on:
      unifi-db:
        condition: service_healthy

  unifi-db:
    image: docker.io/mongo:7
    container_name: unifi-db
    environment:
      - PUID=996
      - PGID=988
      - TZ=Etc/America/New_York
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpasswd
      - MONGO_USER=unifi
      - MONGO_PASS=unifimongopass
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - /mnt/data/docker/volumes/mongo/data:/data/db
      - /mnt/data/docker/volumes/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    restart: unless-stopped
