name: Validate Docker Compose

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '**/docker-compose.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Validate Docker Compose file
      run: |
        docker compose -f docker-compose.yml config
